from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .save_node import (
    NODE_CLASS_MAPPINGS as SAVE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAVE_DISPLAY_MAPPINGS,
)
from .latent_node import (
    NODE_CLASS_MAPPINGS as LATENT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LATENT_DISPLAY_MAPPINGS,
)

NODE_CLASS_MAPPINGS.update(SAVE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LATENT_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SAVE_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LATENT_DISPLAY_MAPPINGS)

WEB_DIRECTORY = "./web/js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
